#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : osm-gps-map
Version  : 1.1.0
Release  : 2
URL      : https://github.com/nzjrs/osm-gps-map/releases/download/1.1.0/osm-gps-map-1.1.0.tar.gz
Source0  : https://github.com/nzjrs/osm-gps-map/releases/download/1.1.0/osm-gps-map-1.1.0.tar.gz
Summary  : Moving map widget using openstreet map data
Group    : Development/Tools
License  : GPL-2.0
Requires: osm-gps-map-data = %{version}-%{release}
Requires: osm-gps-map-lib = %{version}-%{release}
Requires: osm-gps-map-license = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libsoup-2.4)

%description
osm-gps-map is a Gtk mapping widget (and Python bindings) that when given
GPS co-ordinates, draws a GPS track, and points of interest on a moving map
display.

%package data
Summary: data components for the osm-gps-map package.
Group: Data

%description data
data components for the osm-gps-map package.


%package dev
Summary: dev components for the osm-gps-map package.
Group: Development
Requires: osm-gps-map-lib = %{version}-%{release}
Requires: osm-gps-map-data = %{version}-%{release}
Provides: osm-gps-map-devel = %{version}-%{release}
Requires: osm-gps-map = %{version}-%{release}

%description dev
dev components for the osm-gps-map package.


%package doc
Summary: doc components for the osm-gps-map package.
Group: Documentation

%description doc
doc components for the osm-gps-map package.


%package lib
Summary: lib components for the osm-gps-map package.
Group: Libraries
Requires: osm-gps-map-data = %{version}-%{release}
Requires: osm-gps-map-license = %{version}-%{release}

%description lib
lib components for the osm-gps-map package.


%package license
Summary: license components for the osm-gps-map package.
Group: Default

%description license
license components for the osm-gps-map package.


%prep
%setup -q -n osm-gps-map-1.1.0
cd %{_builddir}/osm-gps-map-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581613027
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1581613027
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/osm-gps-map
cp %{_builddir}/osm-gps-map-1.1.0/COPYING %{buildroot}/usr/share/package-licenses/osm-gps-map/2ee57f9bff47f50fe1b9aeaee76d46202876bd04
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/OsmGpsMap-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/osmgpsmap-1.0/osm-gps-map-compat.h
/usr/include/osmgpsmap-1.0/osm-gps-map-image.h
/usr/include/osmgpsmap-1.0/osm-gps-map-layer.h
/usr/include/osmgpsmap-1.0/osm-gps-map-osd.h
/usr/include/osmgpsmap-1.0/osm-gps-map-point.h
/usr/include/osmgpsmap-1.0/osm-gps-map-polygon.h
/usr/include/osmgpsmap-1.0/osm-gps-map-source.h
/usr/include/osmgpsmap-1.0/osm-gps-map-track.h
/usr/include/osmgpsmap-1.0/osm-gps-map-widget.h
/usr/include/osmgpsmap-1.0/osm-gps-map.h
/usr/lib64/libosmgpsmap-1.0.so
/usr/lib64/pkgconfig/osmgpsmap-1.0.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/osm\-gps\-map/*
/usr/share/gtk-doc/html/libosmgpsmap/OsmGpsMap.html
/usr/share/gtk-doc/html/libosmgpsmap/OsmGpsMapImage.html
/usr/share/gtk-doc/html/libosmgpsmap/OsmGpsMapLayer.html
/usr/share/gtk-doc/html/libosmgpsmap/OsmGpsMapPoint.html
/usr/share/gtk-doc/html/libosmgpsmap/OsmGpsMapTrack.html
/usr/share/gtk-doc/html/libosmgpsmap/annotation-glossary.html
/usr/share/gtk-doc/html/libosmgpsmap/api-index-deprecated.html
/usr/share/gtk-doc/html/libosmgpsmap/api-index-full.html
/usr/share/gtk-doc/html/libosmgpsmap/api-reference-deprecated.html
/usr/share/gtk-doc/html/libosmgpsmap/api-reference.html
/usr/share/gtk-doc/html/libosmgpsmap/home.png
/usr/share/gtk-doc/html/libosmgpsmap/index.html
/usr/share/gtk-doc/html/libosmgpsmap/index.sgml
/usr/share/gtk-doc/html/libosmgpsmap/left-insensitive.png
/usr/share/gtk-doc/html/libosmgpsmap/left.png
/usr/share/gtk-doc/html/libosmgpsmap/libosmgpsmap-OsmGpsMap-Deprecated.html
/usr/share/gtk-doc/html/libosmgpsmap/libosmgpsmap.devhelp2
/usr/share/gtk-doc/html/libosmgpsmap/right-insensitive.png
/usr/share/gtk-doc/html/libosmgpsmap/right.png
/usr/share/gtk-doc/html/libosmgpsmap/style.css
/usr/share/gtk-doc/html/libosmgpsmap/up-insensitive.png
/usr/share/gtk-doc/html/libosmgpsmap/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libosmgpsmap-1.0.so.1
/usr/lib64/libosmgpsmap-1.0.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/osm-gps-map/2ee57f9bff47f50fe1b9aeaee76d46202876bd04
